insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(1,'Rektor',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(2,'Majelis Wali Amanat',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(3,'Senat Akademik',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(4,'Wakil Rektor',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(5,'Sekretaris Institut',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(6,'Fakultas',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(7,'Sekolah',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(8,'Direktorat',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(9,'Biro',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(10,'Lembaga',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(11,'Kantor',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(12,'Badan',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(13,'Departemen',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(14,'Program Studi',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(15,'Laboratorium',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(16,'Studio',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(17,'Bengkel',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(18,'Unit Pelaksana Teknis',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(19,'Perpustakaan',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(20,'Pusat Studi',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(21,'Pusat Lain-lain',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(22,'Subdirektorat',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(23,'Seksi',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(24,'Bagian',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(25,'Subbagian',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(26,'Unit',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(27,'Subunit',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(28,'Komite',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(29,'Unit Usaha Komersial',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(30,'Unit Usaha Penunjang',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(31,'Pembantu Rektor',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(32,'Dewan',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(33,'Pusat Penelitian',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(34,'Pusat Unggulan IPTEK',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(35,'Pusat Kajian',Getdate(),Getdate(),Getdate())
insert into JenisSatker(id,nama,create_date,last_update,expired_date)values(36,'Institut',Getdate(),Getdate(),Getdate())